server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: zhaopei
    keyStoreType: PKCS12
    keyAlias: undertom

spring:
  datasource.ecssent:
    driverClassName: oracle.jdbc.driver.OracleDriver
    dbType: oracle
    url: jdbc:oracle:thin:@172.16.149.143:1521:XE
    username: ecssent
    password: 123456
    initialSize: 5
    maxActive: 10
    validationQuery: SELECT 1 from DUAL
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    filters: stat,wall,log4j
  datasource.para:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.16.149.143:1521:XE
    username: para
    password: 123456
    initialSize: 5
    maxActive: 10
    validationQuery: SELECT 1 from DUAL
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    filters: stat,wall,log4j
  datasource.gjent:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.16.149.143:1521:XE
    username: ggfw_zhengzhou
    password: 123456
    initialSize: 5
    maxActive: 10
    validationQuery: SELECT 1 from DUAL
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    filters: stat,wall,log4j
  datasource.gjpayment:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.16.149.143:1521:XE
    username: ggfw_zhengzhou
    password: 123456
    initialSize: 5
    maxActive: 10
    validationQuery: SELECT 1 from DUAL
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    filters: stat,wall,log4j
  datasource.mhin:
    driverClassName: oracle.jdbc.driver.OracleDriver
    dbType: oracle
    url: jdbc:oracle:thin:@172.16.149.143:1521:XE
    username: mh
    password: mh
    initialSize: 5
    maxActive: 10
    validationQuery: SELECT 1 from DUAL
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    filters: stat,wall,log4j
  datasource.mhout:
    driverClassName: oracle.jdbc.driver.OracleDriver
    dbType: oracle
    url: jdbc:oracle:thin:@172.16.149.143:1521:XE
    username: mh
    password: mh
    initialSize: 5
    maxActive: 10
    validationQuery: SELECT 1 from DUAL
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    filters: stat,wall,log4j
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd kk:mm:ss.SSS
    time-zone: GMT+8
  mail:
    host: smtp.126.com
    username: sender000@126.com
    password: password

logging:
  file: maintain.log
  level:
    org:
      mybatis: TRACE
      springframework: INFO
    online.zhaopei.myproject: TRACE

maintain:
  ciqDir: /Users/zhaopei/work/logs/ciq/
  backDir: /Users/zhaopei/work/logs/backCiq/
